import QRCode from "qrcode";
import { createIcons, CircleHelp, Copy, LogOut, Play, RotateCcw, Sparkles, Users, Volume2, VolumeX, X } from "lucide";
import { cardLabel, comboLabel, evaluateCombo, rankLabel, type Card, type Combo } from "../shared/game.ts";
import { playCallout, primeAudio, syncBackgroundMusic, voiceBankForAvatar } from "./audio.ts";
import "./styles.css";
import "./connection.css";

interface PublicPlayer { id:string; name:string; avatar:number; seat:number; team:0|1; bot:boolean; connected:boolean; ready:boolean; cardCount:number }
interface State { room:{code:string;status:"waiting"|"playing"|"result";hostId:string;playerId:string;gameIndex:number;players:PublicPlayer[]}; game:null|{level:number;levels:[number,number];hand:Card[];currentSeat:number;currentCombo:Combo|null;currentComboLabel:string;lastPlayerId:string|null;finishOrder:string[];passedIds:string[];deadline:number;canPass:boolean;legalHint:string[];interaction?:{playerId:string;text:string;tone:"team"|"block"|"bomb"|"normal"};trickActions:Array<{playerId:string;combo?:Combo;passed:boolean}>;audioAction?:{serial:number;playerId:string;combo?:Combo;passed:boolean};result:{winner:0|1;levels:number}|null} }
interface Session { code:string;playerId:string;sessionToken:string }

const app = document.querySelector<HTMLDivElement>("#app")!;
const icons = { CircleHelp, Copy, LogOut, Play, RotateCcw, Sparkles, Users, Volume2, VolumeX, X };
let state: State | null = null; let ws: WebSocket | null = null; let connected = false; let pollTimer: number | null = null; let reconnectTimer: number | null = null; let selected = new Set<string>(); let toast = ""; let timer: number | null = null;
let soundEnabled = localStorage.getItem("guandan-sound") !== "off"; let audioContext: AudioContext | null = null; let comboEffect: {kind:string;title:string;detail:string}|null = null; let effectTimer:number|null=null;
const saved = localStorage.getItem("guandan-session"); let session: Session | null = saved ? JSON.parse(saved) : null;
const profile = JSON.parse(localStorage.getItem("guandan-profile") || '{"name":"牌友","avatar":0}');
const joinParam = new URLSearchParams(location.search).get("join") || "";

function escape(value:string){return value.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]!)}
function suit(card:Card){return card.suit==="hearts"?"♥":card.suit==="diamonds"?"♦":card.suit==="clubs"?"♣":card.suit==="spades"?"♠":"★"}
function cardHtml(card:Card,stackIndex=0){const red=card.suit==="hearts"||card.suit==="diamonds";const joker=card.suit==="joker";const court=card.rank>=11&&card.rank<=13;const label=cardLabel(card);const pip=suit(card);const corner=joker?`<span class="card-corner joker-corner"><b>★</b></span>`:`<span class="card-corner"><b>${label}</b><em>${pip}</em></span>`;const mirrored=`<span class="card-corner mirrored"><b>${label}</b><em>${pip}</em></span>`;const face=joker?`<span class="joker-figure"></span><strong class="joker-name">${label}</strong>`:court?`<span class="court-figure court-${label.toLowerCase()}"></span>${mirrored}`:`<span class="card-center">${pip}</span>${mirrored}`;return `<button class="card ${red?"red":""} ${joker?`joker joker-${card.rank===17?"big":"small"}`:""} ${court?"court":""} ${selected.has(card.id)?"selected":""}" style="--stack-index:${stackIndex}" data-card="${card.id}" aria-label="${label}${pip}">${corner}${face}${card.suit==="hearts"&&card.rank===state?.game?.level?'<i>配</i>':""}</button>`}
function groupedHand(cards:Card[]){const groups:Card[][]=[];for(const card of cards){const key=cardLabel(card);const group=groups.find(item=>cardLabel(item[0])===key);if(group)group.push(card);else groups.push([card])}const maxStack=Math.max(...groups.map(group=>group.length),1);const step=Math.max(14,Math.min(23,Math.floor(98/Math.max(1,maxStack-1))));return `<div class="cards" style="--hand-groups:${groups.length};--stack-step:${step}px">${groups.map(group=>`<div class="card-group">${group.map((card,index)=>cardHtml(card,index)).join("")}</div>`).join("")}</div>`}
function seats(){const me=state!.room.players.find(p=>p.id===state!.room.playerId)!;return [0,1,2,3].map(offset=>state!.room.players.find(p=>p.seat===(me.seat+offset)%4)!)}
function relation(player:PublicPlayer){const me=state?.room.players.find(item=>item.id===state?.room.playerId);if(!me)return null;if(player.id===me.id)return {kind:"self",label:"我"};return player.team===me.team?{kind:"mate",label:"队友"}:{kind:"rival",label:"对手"}}
function avatar(player:PublicPlayer,tagged=false){const picture=`<span class="avatar a${player.avatar%8}" aria-label="${escape(player.name)}"></span>`;const role=relation(player);return tagged&&role?`<span class="avatar-wrap">${picture}<i class="relation ${role.kind}">${role.label}</i></span>`:picture}
function sound(name:"select"|"play"|"pass"|"turn"|"bomb"|"mega"|"flush"|"win"|"lose"){if(!soundEnabled)return;const context=audioContext||new AudioContext();audioContext=context;if(context.state==="suspended")void context.resume();const patterns={select:[[620,0,.035]],play:[[260,0,.045],[170,.045,.065]],pass:[[210,0,.08]],turn:[[520,0,.07],[740,.09,.11]],bomb:[[105,0,.16],[72,.06,.25]],mega:[[105,0,.18],[68,.05,.32],[52,.14,.38]],flush:[[420,0,.08],[560,.06,.1],[720,.14,.17]],win:[[440,0,.08],[554,.1,.08],[659,.2,.18]],lose:[[260,0,.12],[196,.13,.2]]} as const;for(const [frequency,delay,duration] of patterns[name]){const oscillator=context.createOscillator();const gain=context.createGain();oscillator.type=name==="bomb"||name==="mega"?"sawtooth":"sine";oscillator.frequency.setValueAtTime(frequency,context.currentTime+delay);gain.gain.setValueAtTime(.0001,context.currentTime+delay);gain.gain.exponentialRampToValueAtTime((name==="bomb"||name==="mega")?0.12:0.055,context.currentTime+delay+.008);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+delay+duration);oscillator.connect(gain).connect(context.destination);oscillator.start(context.currentTime+delay);oscillator.stop(context.currentTime+delay+duration+.02)}}
function vibrate(pattern:number|number[]){navigator.vibrate?.(pattern)}
function effectFor(combo?:Combo){if(!combo)return null;if(combo.type==="straight-flush")return {kind:"flush",title:"同花顺",detail:"一色贯穿"};if(combo.type==="joker-bomb")return {kind:"mega",title:"四王炸",detail:"王牌封顶"};if(combo.type!=="bomb")return null;if(combo.size===4)return {kind:"four",title:"四炸",detail:"炸弹压场"};if(combo.size===5)return {kind:"five",title:"五炸",detail:"火力升级"};return {kind:"mega",title:`${combo.size} 张炸`,detail:"全场震动"}}
function showEffect(effect:ReturnType<typeof effectFor>){if(!effect)return;comboEffect=effect;if(effectTimer)clearTimeout(effectTimer);render();effectTimer=window.setTimeout(()=>{comboEffect=null;effectTimer=null;render()},850)}
function effectHtml(){if(!comboEffect)return "";const cards=comboEffect.kind==="flush"?"<div class=effect-cards><i>10♥</i><i>J♥</i><i>Q♥</i><i>K♥</i><i>A♥</i></div>":"<div class=effect-burst><i></i><i></i><i></i></div>";return `<div class="combo-effect ${comboEffect.kind}">${cards}<div class="effect-copy"><b>${comboEffect.title}</b><span>${comboEffect.detail}</span></div></div>`}
function playStateSound(previous:State|null,next:State){if(!previous)return;if(previous.room.status!=="result"&&next.room.status==="result"){const me=next.room.players.find(player=>player.id===next.room.playerId);sound(next.game?.result?.winner===me?.team?"win":"lose");return}const action=next.game?.audioAction;if(action&&action.serial!==previous.game?.audioAction?.serial){const effect=effectFor(action.combo);const speaker=next.room.players.find(player=>player.id===action.playerId);playCallout(action.combo,action.passed,soundEnabled,voiceBankForAvatar(speaker?.avatar??0));if(effect){showEffect(effect);sound(effect.kind==="flush"?"flush":effect.kind==="four"?"bomb":"mega");vibrate(effect.kind==="four"?[30,35,45]:[35,30,55,35,70])}else sound(action.passed?"pass":"play")}if(previous.game?.currentSeat!==next.game?.currentSeat&&next.room.players.find(player=>player.id===next.room.playerId)?.seat===next.game?.currentSeat)sound("turn")}
function hydrate(){createIcons({icons});document.querySelectorAll<HTMLElement>(".level-score b").forEach(element=>{element.textContent=rankLabel(Number(element.textContent))});syncBackgroundMusic(soundEnabled,state?.room.status==="playing")}
function notice(message:string){toast=message;render();setTimeout(()=>{toast="";render()},1800)}

function home(){return `<main class="home"><section class="home-visual"><div class="home-brand"><span>完整 108 张 · 四人两队</span><h1>搭子掼蛋</h1><p>对家是队友，一把见配合</p></div><div class="card-fan"><i></i><i></i><i></i><i></i></div><div class="home-relations"><span><i></i>对家队友</span><span><i></i>左右对手</span></div></section><section class="entry"><div class="profile-entry"><label>你的称呼<input id="name" maxlength="12" value="${escape(profile.name)}"></label><div class="avatar-pick"><button id="avatar">${avatar({name:profile.name,avatar:profile.avatar} as PublicPlayer)}<span>换头像</span></button></div></div>${joinParam?`<button class="primary" id="quick-join"><i data-lucide="users"></i>加入 ${escape(joinParam)}</button>`:`<button class="primary" id="create"><i data-lucide="play"></i>创建四人牌桌</button><div class="join"><input id="code" maxlength="6" placeholder="输入房间号"><button id="join">加入</button></div>`}<button class="rules" id="rules"><i data-lucide="circle-help"></i>玩法说明</button></section></main>`}
function waiting(){const me=state!.room.players.find(p=>p.id===state!.room.playerId)!;const host=me.id===state!.room.hostId;return `<main class="waiting"><header><button id="leave" class="icon" title="离开房间"><i data-lucide="log-out"></i></button><div><small>四人搭子局</small><h1>房间 ${state!.room.code}</h1></div><button id="copy" class="icon" title="复制邀请链接"><i data-lucide="copy"></i></button></header><section class="invite"><div id="qr"></div><div><b>${state!.room.players.filter(p=>!p.bot).length}/4 人已加入</b><p>绿标是队友，红标是对手</p></div></section><section class="seats">${[0,1,2,3].map(seat=>{const p=state!.room.players.find(x=>x.seat===seat);return `<div class="seat team${seat%2}">${p?`${avatar(p,true)}<b>${escape(p.name)}</b><small>${p.id===me.id?"当前座位":p.team===me.team?"坐在你的对面":"坐在你的侧边"}</small>`:`<span class="empty">+</span><b>等待加入</b><small>${seat%2===me.seat%2?"你的队友":"对手"}</small>`}</div>`}).join("")}</section><div class="wait-note"><b>完整打一把</b><span>两副牌、每人 27 张，预计 8～15 分钟</span></div>${host?`<button class="primary dock" id="start" ${connected?"":"disabled"}><i data-lucide="play"></i>${connected?(state!.room.players.filter(p=>!p.bot).length<4?"人机补位并开局":"开始发牌"):"正在恢复房间连接"}</button>`:`<div class="waiting-host">${connected?"等待房主开始":"正在恢复房间连接"}</div>`}</main>`}
function playerSeat(player:PublicPlayer,position:string){const acting=state?.game?.currentSeat===player.seat;return `<div class="opponent ${position} ${acting?"acting":""}">${avatar(player,true)}<b>${escape(player.name)}</b><span>${player.cardCount} 张</span></div>`}
function selectionLabel(combo:Combo|null,noBeat=false){if(noBeat)return "没有比这个更大的牌";if(combo)return `已选 ${selected.size} 张 · ${comboLabel(combo)}`;return selected.size?`已选 ${selected.size} 张 · 牌型不成立`:"点选手牌"}
function table(){const [me,right,partner,left]=seats();const game=state!.game!;const myTurn=me.seat===game.currentSeat;const combo=selectedCombo();const noBeat=myTurn&&Boolean(game.currentCombo)&&game.canPass&&game.legalHint.length===0;const talking=game.interaction?state!.room.players.find(p=>p.id===game.interaction!.playerId):null;return `<main class="game"><header><span>打 <b>${game.level>10?({11:"J",12:"Q",13:"K",14:"A"} as any)[game.level]:game.level}</b></span><strong>${state!.room.code}</strong><div class="game-tools"><span id="clock">--</span><button id="sound" class="sound-toggle" title="${soundEnabled?"关闭音效":"开启音效"}" aria-label="${soundEnabled?"关闭音效":"开启音效"}"><i data-lucide="${soundEnabled?"volume-2":"volume-x"}"></i></button></div></header><section class="table"><div class="team-mark">${me.team===0?"青队":"金队"}<small>绿色是队友 · 红色是对手</small></div>${playerSeat(partner,"top")}${playerSeat(right,"side right")}${playerSeat(left,"side left")}${playerSeat(me,"bottom")}${talking&&game.interaction?`<div class="bot-talk ${game.interaction.tone}"><b>${escape(talking.name)}</b><span>${escape(game.interaction.text)}</span></div>`:""}<div class="trick-center"><small>${game.currentCombo?"当前要压":"新一轮"}</small><b>${game.currentComboLabel}</b></div>${seatPlay(partner,"play-top")}${seatPlay(right,"play-right")}${seatPlay(left,"play-left")}${seatPlay(me,"play-bottom")}<div class="turn ${myTurn?"active":""}">${myTurn?(noBeat?"无牌可压":"轮到你出牌"):`等待 ${escape(state!.room.players.find(p=>p.seat===game.currentSeat)?.name||"")}`}</div></section><section class="hand ${noBeat?"cannot-beat":""}"><div class="hand-meta"><span>我的手牌 <b>${game.hand.length}</b></span><span>${selectionLabel(combo,noBeat)}</span></div>${groupedHand(game.hand)}<footer>${noBeat?`<button id="pass" class="primary no-beat-action">没有更大的牌 · 不要</button>`:`<button id="hint" class="secondary"><i data-lucide="sparkles"></i>提示</button>${game.canPass?`<button id="pass" class="secondary">不要</button>`:""}<button id="play" class="primary" ${!myTurn||!combo?"disabled":""}>出牌</button>`}</footer></section></main>`}
function cardHtmlStatic(card:Card){const red=card.suit==="hearts"||card.suit==="diamonds";const joker=card.suit==="joker";const court=card.rank>=11&&card.rank<=13;const label=cardLabel(card);const pip=suit(card);return `<i class="mini-card ${red?"red":""} ${joker?`mini-joker mini-joker-${card.rank===17?"big":"small"}`:""} ${court?`mini-court mini-court-${label.toLowerCase()}`:""}"><span class="mini-corner">${joker?"★":`${label}${pip}`}</span>${joker?`<span class="mini-joker-figure"></span>`:court?`<span class="mini-court-figure"></span>`:`<span class="mini-center">${pip}</span>`}</i>`}
function seatPlay(player:PublicPlayer,position:string){const action=state?.game?.trickActions.find(item=>item.playerId===player.id);if(!action)return "";return `<div class="seat-play ${position} ${action.passed?"passed":""}"><small>${escape(player.name)}</small>${action.passed?`<b>不要</b>`:`<div>${action.combo?.cards.map(cardHtmlStatic).join("")||""}</div><b>${comboLabel(action.combo||null)}</b>`}</div>`}
function selectedCombo(){if(!state?.game)return null;const chosen=[...selected].map(id=>state!.game!.hand.find(card=>card.id===id)).filter(Boolean) as Card[];return chosen.length?evaluateCombo(chosen,state.game.level):null}
function updateSelectionUi(){if(!state?.game)return;document.querySelectorAll<HTMLElement>("[data-card]").forEach(element=>element.classList.toggle("selected",selected.has(element.dataset.card||"")));const combo=selectedCombo();const me=state.room.players.find(player=>player.id===state!.room.playerId);const noBeat=me?.seat===state.game.currentSeat&&Boolean(state.game.currentCombo)&&state.game.canPass&&state.game.legalHint.length===0;const label=document.querySelector<HTMLElement>(".hand-meta span:last-child");if(label)label.textContent=selectionLabel(combo,noBeat);const play=document.querySelector<HTMLButtonElement>("#play");if(play)play.disabled=!combo||me?.seat!==state.game.currentSeat}
function result(){const game=state!.game!;const me=state!.room.players.find(p=>p.id===state!.room.playerId)!;const won=game.result?.winner===me.team;const myTeam=me.team===0?"青队":"金队";const otherTeam=me.team===0?"金队":"青队";return `<main class="result ${won?"win":"lose"}"><div class="result-top"><small>完整一把结束</small><h1>${won?"搭子配合到位":"这把还没接上"}</h1><p>${won?`${myTeam}升级 ${game.result?.levels} 级`:`${otherTeam}升级 ${game.result?.levels} 级`}</p><div class="result-team-map"><span class="qing"><b>青队</b><em>${me.team===0?"我方":"对方"}</em></span><span class="gold"><b>金队</b><em>${me.team===1?"我方":"对方"}</em></span></div></div><section class="order">${game.finishOrder.map((id,index)=>{const p=state!.room.players.find(x=>x.id===id)!;return `<div class="team-${p.team===0?"qing":"gold"} ${p.team===me.team?"mine":""}"><b>${index+1}</b>${avatar(p,true)}<span>${escape(p.name)}</span><small class="result-team-tag ${p.team===0?"qing":"gold"}">${p.team===0?"青队":"金队"}</small></div>`}).join("")}</section><div class="level-score"><div class="qing"><small>青队级数</small><b>${game.levels[0]}</b></div><i></i><div class="gold"><small>金队级数</small><b>${game.levels[1]}</b></div></div><footer><button id="ready" class="primary"><i data-lucide="rotate-ccw"></i>继续升级</button><button id="leave" class="secondary">继续唱歌</button></footer></main>`}
function rules(){return `<div class="modal" id="modal"><button id="close" class="icon"><i data-lucide="x"></i></button><small>15 秒看懂</small><h2>不是缩牌版，规则完整</h2><div class="rule-grid"><div><b>1</b><span><strong>四人两队</strong>坐你对面的人是搭档。</span></div><div><b>2</b><span><strong>每人 27 张</strong>保留逢人配、同花顺和多级炸弹。</span></div><div><b>3</b><span><strong>先出完争头游</strong>还要给搭档留接风和出牌权。</span></div><div><b>4</b><span><strong>打一把就能停</strong>续局才继承级数，不强制打到 A。</span></div></div><button id="close2" class="primary">知道了</button></div>`}
let modal=false;
function render(){let html=!state?home():state.room.status==="waiting"?waiting():state.room.status==="playing"?table():result();if(state&&!connected)html+=`<div class="connection">连接中断，正在恢复</div>`;if(modal)html+=rules();if(toast)html+=`<div class="toast">${escape(toast)}</div>`;html+=effectHtml();app.innerHTML=html;hydrate();bind();if(state?.room.status==="waiting")drawQr();countdown()}

async function api(path:string,data:any){const response=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const json=await response.json();if(!response.ok)throw new Error(json.error);return json}
function saveProfile(){const input=document.querySelector<HTMLInputElement>("#name");if(input)profile.name=input.value.trim()||"牌友";localStorage.setItem("guandan-profile",JSON.stringify(profile))}
async function create(){saveProfile();setSession(await api("/api/rooms",profile))}
async function join(code:string){saveProfile();setSession(await api(`/api/rooms/${code.trim().toUpperCase()}/join`,profile))}
function setSession(value:Session){session=value;localStorage.setItem("guandan-session",JSON.stringify(value));connect()}
function stateSignature(value:State){return JSON.stringify({status:value.room.status,host:value.room.hostId,players:value.room.players.map(player=>[player.id,player.connected,player.cardCount,player.ready]),turn:value.game?.currentSeat,hand:value.game?.hand.map(card=>card.id),combo:value.game?.currentCombo?.cards.map(card=>card.id),trick:value.game?.trickActions.map(action=>[action.playerId,action.passed,action.combo?.cards.map(card=>card.id)]),talk:value.game?.interaction,finish:value.game?.finishOrder,result:value.game?.result})}
function applyState(next:State,clearSelection=false){const previous=state;const changed=!state||stateSignature(state)!==stateSignature(next);state=next;connected=true;if(clearSelection)selected.clear();else selected=new Set([...selected].filter(id=>next.game?.hand.some(card=>card.id===id)));if(changed)render();else updateSelectionUi();playStateSound(previous,next)}
function expireSession(){session=null;state=null;connected=false;localStorage.removeItem("guandan-session");if(pollTimer)clearInterval(pollTimer);pollTimer=null;render();notice("原房间已失效，请重新创建或加入")}
async function pollState(){if(!session)return;const response=await fetch(`/api/rooms/${session.code}/state?player=${encodeURIComponent(session.playerId)}&token=${encodeURIComponent(session.sessionToken)}`,{cache:"no-store"});if(response.status===404){expireSession();return}if(!response.ok)throw new Error("房间同步失败");applyState(await response.json())}
function startPolling(){if(pollTimer||!session)return;pollState().catch(()=>{connected=false;render()});pollTimer=window.setInterval(()=>pollState().catch(()=>{connected=false;render()}),1000)}
function stopPolling(){if(pollTimer)clearInterval(pollTimer);pollTimer=null}
function connect(){if(!session)return;const currentSession=session;const previous=ws;ws=null;previous?.close();connected=false;const scheme=location.protocol==="https:"?"wss":"ws";const socket=new WebSocket(`${scheme}://${location.host}/ws?room=${currentSession.code}&player=${currentSession.playerId}&token=${currentSession.sessionToken}`);ws=socket;socket.onopen=()=>{if(ws!==socket)return;stopPolling();connected=true;render()};socket.onmessage=e=>{if(ws!==socket)return;const m=JSON.parse(e.data);if(m.type==="state")applyState(m);else if(m.type==="error")notice(m.message)};socket.onclose=event=>{if(ws!==socket)return;ws=null;if(event.code===1008){expireSession();return}startPolling();if(reconnectTimer)clearTimeout(reconnectTimer);reconnectTimer=window.setTimeout(()=>session&&connect(),5000)}}
async function send(action:string,data:any={}){const payload={action,requestId:crypto.randomUUID(),...data};if(ws?.readyState===WebSocket.OPEN){ws.send(JSON.stringify(payload));return}if(!session){notice("房间已失效");return}try{const response=await fetch(`/api/rooms/${session.code}/action`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,playerId:session.playerId,sessionToken:session.sessionToken})});const result=await response.json();if(response.status===404){expireSession();return}if(!response.ok)throw new Error(result.error||"操作失败");applyState(result,true);startPolling()}catch(error){notice(error instanceof Error?error.message:"房间连接尚未恢复")}}
function leave(){session=null;state=null;connected=false;localStorage.removeItem("guandan-session");ws?.close();stopPolling();if(reconnectTimer)clearTimeout(reconnectTimer);history.replaceState({},"",location.pathname);render()}
async function drawQr(){const el=document.querySelector("#qr");if(!el||!state)return;const canvas=document.createElement("canvas");await QRCode.toCanvas(canvas,`${location.origin}${location.pathname}?join=${state.room.code}`,{width:110,margin:1});el.replaceChildren(canvas)}
function countdown(){if(timer)clearInterval(timer);if(state?.room.status!=="playing")return;timer=window.setInterval(()=>{const el=document.querySelector("#clock");if(el&&state?.game)el.textContent=String(Math.max(0,Math.ceil((state.game.deadline-Date.now())/1000)))},250)}
function bind(){document.querySelector("#create")?.addEventListener("click",()=>create().catch(e=>notice(e.message)));document.querySelector("#quick-join")?.addEventListener("click",()=>join(joinParam).catch(e=>notice(e.message)));document.querySelector("#join")?.addEventListener("click",()=>join((document.querySelector<HTMLInputElement>("#code")?.value||"")).catch(e=>notice(e.message)));document.querySelector("#avatar")?.addEventListener("click",()=>{profile.avatar=(profile.avatar+1)%8;saveProfile();sound("select");render()});document.querySelectorAll("#rules").forEach(e=>e.addEventListener("click",()=>{modal=true;render()}));document.querySelectorAll("#close,#close2").forEach(e=>e.addEventListener("click",()=>{modal=false;render()}));document.querySelectorAll("#leave").forEach(e=>e.addEventListener("click",leave));document.querySelector("#copy")?.addEventListener("click",async()=>{await navigator.clipboard?.writeText(`${location.origin}${location.pathname}?join=${state?.room.code}`);notice("邀请链接已复制")});document.querySelector("#sound")?.addEventListener("click",()=>{soundEnabled=!soundEnabled;localStorage.setItem("guandan-sound",soundEnabled?"on":"off");if(soundEnabled)sound("turn");render()});document.querySelector("#start")?.addEventListener("click",()=>{sound("play");send("start_game")});document.querySelectorAll<HTMLElement>("[data-card]").forEach(element=>element.addEventListener("click",()=>{const id=element.dataset.card!;if(selected.has(id))selected.delete(id);else selected.add(id);sound("select");vibrate(8);updateSelectionUi()}));document.querySelector("#hint")?.addEventListener("click",()=>{const hint=state?.game?.legalHint||[];const alreadySelected=hint.length===selected.size&&hint.every(id=>selected.has(id));selected=alreadySelected?new Set():new Set(hint);sound("select");vibrate(12);updateSelectionUi()});document.querySelector("#pass")?.addEventListener("click",()=>{vibrate(18);send("pass")});document.querySelector("#play")?.addEventListener("click",()=>{vibrate([12,20,18]);send("play",{cardIds:[...selected]})});document.querySelector("#ready")?.addEventListener("click",()=>{send("ready");if(state?.room.hostId===state?.room.playerId)setTimeout(()=>send("start_game"),300)})}
document.addEventListener("pointerdown",()=>{if(soundEnabled&&audioContext===null)audioContext=new AudioContext();primeAudio(soundEnabled)},{once:true});
document.addEventListener("visibilitychange",()=>syncBackgroundMusic(soundEnabled&&!document.hidden,state?.room.status==="playing"));
if(session)connect();else render();
