import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { chromium } from "playwright";

const output=path.resolve("output/verification");fs.mkdirSync(output,{recursive:true});
const port=4542;const deployed=Boolean(process.env.VERIFY_URL);const baseUrl=process.env.VERIFY_URL||`http://127.0.0.1:${port}`;
const server=process.env.VERIFY_URL?null:spawn(process.execPath,["--import","tsx","server/index.ts"],{cwd:process.cwd(),env:{...process.env,PORT:String(port),TURN_MS:"5000"},stdio:"ignore"});
async function wait(){for(let i=0;i<80;i++){try{if((await fetch(`${baseUrl}/api/health`)).ok)return}catch{/* server starting */}await new Promise(r=>setTimeout(r,process.env.VERIFY_URL?500:100))}throw new Error("server failed")}
async function captureEffect(page,kind,title,detail){await page.evaluate(({kind,title,detail})=>{document.querySelector(".combo-effect")?.remove();const visual=kind==="flush"?"<div class=effect-cards><i>10♥</i><i>J♥</i><i>Q♥</i><i>K♥</i><i>A♥</i></div>":"<div class=effect-burst><i></i><i></i><i></i></div>";document.body.insertAdjacentHTML("beforeend",`<div class="combo-effect ${kind}">${visual}<div class="effect-copy"><b>${title}</b><span>${detail}</span></div></div>`)},{kind,title,detail});await page.waitForTimeout(180);await page.screenshot({path:path.join(output,`effect-${kind}-mobile.png`),fullPage:true});await page.evaluate(()=>document.querySelector(".combo-effect")?.remove())}
async function postApi(pathname,data){const response=await fetch(`${baseUrl}${pathname}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const body=await response.json();if(!response.ok)throw new Error(body.error||`${pathname} returned ${response.status}`);return body}
async function roomState(session){const response=await fetch(`${baseUrl}/api/rooms/${session.code}/state?player=${session.playerId}&token=${session.sessionToken}`);const body=await response.json();if(!response.ok)throw new Error(body.error||"state failed");return body}
async function roomAction(session,action,data={}){return postApi(`/api/rooms/${session.code}/action`,{action,requestId:crypto.randomUUID(),playerId:session.playerId,sessionToken:session.sessionToken,...data})}
async function prepareTributeRoom(){for(let attempt=0;attempt<4;attempt++){const owner=await postApi("/api/rooms",{name:"贡牌验收"});const sessions=[owner];for(let index=1;index<4;index++)sessions.push(await postApi(`/api/rooms/${owner.code}/join`,{name:`验收玩家${index+1}`}));let state=await roomAction(owner,"start_game");for(let step=0;step<500&&state.room.status==="playing";step++){const current=state.room.players.find(player=>player.seat===state.game.currentSeat);const session=sessions.find(item=>item.playerId===current.id);const privateState=await roomState(session);state=privateState.game.legalHint.length?await roomAction(session,"play",{cardIds:privateState.game.legalHint}):await roomAction(session,"pass")}if(state.room.status!=="result")throw new Error("automated game did not finish");const tributeState=await roomAction(owner,"start_game");if(tributeState.room.status!=="tribute"||!tributeState.game.tribute)throw new Error("rematch did not enter tribute");if(tributeState.game.tribute.anti)continue;const chosenReceiverId=tributeState.game.tribute.pairs[0].receiverId;const chosenSession=sessions.find(item=>item.playerId===chosenReceiverId);for(const session of sessions){if(session.playerId===chosenReceiverId)continue;const privateState=await roomState(session);const option=privateState.game.tribute?.returnOptions[0];if(option)await roomAction(session,"return_tribute",{cardId:option})}return{session:chosenSession,tribute:tributeState.game.tribute}}throw new Error("could not prepare a non-anti tribute room")}
try{
  await wait();const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});const audioResponses=new Set();page.on("response",response=>{if(response.url().includes("/assets/audio/")&&response.ok())audioResponses.add(new URL(response.url()).pathname)});
  await page.addInitScript(()=>localStorage.setItem("guandan-session",JSON.stringify({code:"STALE1",playerId:"gone",sessionToken:"expired"})));
  await page.goto(baseUrl);await page.waitForSelector(".home");await page.waitForTimeout(1900);await page.screenshot({path:path.join(output,"home-mobile.png"),fullPage:true});
  const homeLayout=await page.evaluate(()=>{const home=document.querySelector(".home")?.getBoundingClientRect();const visual=document.querySelector(".home-visual")?.getBoundingClientRect();const entry=document.querySelector(".entry")?.getBoundingClientRect();return{bottom:home?.bottom,gap:entry&&visual?entry.top-visual.bottom:null,viewport:innerHeight}});
  if(homeLayout.bottom!==homeLayout.viewport||homeLayout.gap!==0)throw new Error(`home layout has a gap ${JSON.stringify(homeLayout)}`);
  await page.setViewportSize({width:430,height:932});await page.screenshot({path:path.join(output,"home-tall-mobile.png"),fullPage:true});await page.setViewportSize({width:390,height:844});
  await page.getByRole("button",{name:/创建四人牌桌/}).click();await page.waitForSelector(".waiting");await page.screenshot({path:path.join(output,"waiting-mobile.png"),fullPage:true});
  await page.getByRole("button",{name:/人机补位并开局/}).click();await page.waitForSelector(".game");
  const initialCards=await page.locator(".cards .card").count();
  if(!deployed){const stackedGroup=await page.evaluate(()=>[...document.querySelectorAll(".card-group")].findIndex(group=>group.querySelectorAll(".card").length>1));const stackedCards=page.locator(".card-group").nth(stackedGroup).locator(".card");await stackedCards.nth(0).click({position:{x:6,y:6}});await stackedCards.nth(1).click({position:{x:6,y:6}});if(await page.locator(".cards .card.selected").count()!==2)throw new Error("stacked card selection did not persist");await stackedCards.nth(0).click({position:{x:6,y:6}});await stackedCards.nth(1).click({position:{x:6,y:6}});await page.locator(".card-group").nth(0).locator(".card").last().click();await page.locator(".card-group").nth(1).locator(".card").last().click();if(await page.locator(".cards .card.selected").count()!==2)throw new Error("consecutive card selection did not persist");await page.locator(".card-group").nth(0).locator(".card").last().click();await page.locator(".card-group").nth(1).locator(".card").last().click()}
  if(await page.locator("#hint").count()){await page.locator("#hint").click();const hinted=await page.locator(".cards .card.selected").count();if(hinted<1)throw new Error("hint did not select cards");await page.locator("#hint").click();if(await page.locator(".cards .card.selected").count()!==0)throw new Error("second hint click did not clear cards");await page.locator("#hint").click();if(await page.locator(".cards .card.selected").count()!==hinted)throw new Error("hint did not restore cards");}
  await page.screenshot({path:path.join(output,"game-mobile.png"),fullPage:true});
  const checks=await page.evaluate(()=>{const cards=[...document.querySelectorAll(".cards .card")];const groups=[...document.querySelectorAll(".card-group")];const tray=document.querySelector(".cards");const avatar=document.querySelector(".avatar");const table=document.querySelector(".table");return{cards:cards.length,groups:groups.length,stacked:groups.some(group=>group.querySelectorAll(".card").length>1&&new Set([...group.querySelectorAll(".card")].map(card=>card.offsetTop)).size>1),labelsVisible:groups.every(group=>{const stack=[...group.querySelectorAll(".card")];return stack.slice(0,-1).every((card,index)=>(card.querySelector("b")?.getBoundingClientRect().bottom||Infinity)<=stack[index+1].getBoundingClientRect().top)}),relations:document.querySelectorAll(".relation").length,avatarAsset:avatar?getComputedStyle(avatar).backgroundImage.includes("avatar-atlas-v1"):false,tableAsset:table?getComputedStyle(table).backgroundImage.includes("table-felt-v2"):false,trayScroll:tray?.scrollWidth,trayWidth:tray?.clientWidth,trayOverflow:tray?getComputedStyle(tray).overflowX:"",width:document.documentElement.scrollWidth,viewport:innerWidth,text:document.body.innerText.includes("我的手牌")}});
  if(initialCards!==27||checks.cards>27||checks.cards<1||checks.groups<1||checks.groups>15||!checks.stacked||!checks.labelsVisible||checks.relations!==4||!checks.avatarAsset||!checks.tableAsset||checks.trayScroll!==checks.trayWidth&&checks.trayOverflow!=="hidden"||checks.width>checks.viewport||!checks.text)throw new Error(`browser checks failed ${JSON.stringify({initialCards,...checks})}`);
  if(await page.locator("#play").isEnabled())await page.locator("#play").click();
  await page.waitForFunction(()=>document.querySelectorAll(".seat-play").length>=2);
  const seatActions=await page.locator(".seat-play").count();
  const playedFaces=await page.evaluate(()=>{const cards=[...document.querySelectorAll(".seat-play .mini-card")];return{cards:cards.length,detailed:cards.every(card=>Boolean(card.querySelector(".mini-corner")&&(card.querySelector(".mini-center")||card.querySelector(".mini-court-figure")||card.querySelector(".mini-joker-figure"))))}});
  if(!playedFaces.cards||!playedFaces.detailed)throw new Error(`played cards do not use detailed faces ${JSON.stringify(playedFaces)}`);
  await page.waitForTimeout(600);const audioAssets={bgm:[...audioResponses].some(url=>url.endsWith("bgm-table.wav")),edgeCallouts:[...audioResponses].filter(url=>url.includes("/edge-")&&url.endsWith(".mp3")).length};
  if(!audioAssets.bgm||audioAssets.edgeCallouts<1)throw new Error(`audio assets were not loaded ${JSON.stringify(audioAssets)}`);
  const audioDurations=await page.evaluate(async()=>{const context=new AudioContext();try{const results=[];for(const file of ["/assets/audio/bgm-table.wav","/assets/audio/edge-male/rank-7.mp3","/assets/audio/edge-female/pair.mp3","/assets/audio/edge-male/straight-flush.mp3"]){const response=await fetch(`${file}?verify=${Date.now()}`,{cache:"no-store"});if(!response.ok)throw new Error(`${file} returned ${response.status}`);const data=await response.arrayBuffer();const decoded=await context.decodeAudioData(data);results.push({file,duration:decoded.duration,type:response.headers.get("content-type")})}return results}finally{await context.close()}});
  if(audioDurations.some(item=>!Number.isFinite(item.duration)||item.duration<.2))throw new Error(`audio metadata is invalid ${JSON.stringify(audioDurations)}`);
  if(audioDurations.filter(item=>item.file.endsWith(".mp3")).some(item=>item.type!=="audio/mpeg"))throw new Error(`audio MIME type is invalid ${JSON.stringify(audioDurations)}`);
  await page.screenshot({path:path.join(output,"game-trick-actions-mobile.png"),fullPage:true});
  await page.setViewportSize({width:890,height:1197});await page.screenshot({path:path.join(output,"game-desktop.png"),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await captureEffect(page,"four","四炸","炸弹压场");await captureEffect(page,"five","五炸","火力升级");await captureEffect(page,"flush","同花顺","一色贯穿");
  const tributeSetup=await prepareTributeRoom();const tributePage=await browser.newPage({viewport:{width:390,height:844}});await tributePage.addInitScript(session=>localStorage.setItem("guandan-session",JSON.stringify(session)),tributeSetup.session);await tributePage.goto(baseUrl);await tributePage.waitForSelector(".tribute");const tributeChecks=await tributePage.evaluate(()=>({pairs:document.querySelectorAll(".tribute-pair").length,cards:document.querySelectorAll(".tribute-hand .card").length,width:document.documentElement.scrollWidth,viewport:innerWidth,text:document.body.innerText.includes("请选择还贡牌")}));if(tributeChecks.pairs!==tributeSetup.tribute.pairs.length||tributeChecks.cards<1||tributeChecks.width>tributeChecks.viewport||!tributeChecks.text)throw new Error(`tribute UI checks failed ${JSON.stringify(tributeChecks)}`);await tributePage.screenshot({path:path.join(output,"tribute-mobile.png"),fullPage:true});await tributePage.locator(".tribute-hand .card").last().click();if(!await tributePage.locator("#return-tribute").isEnabled())throw new Error("tribute return button did not enable");await tributePage.locator("#return-tribute").click();await tributePage.waitForSelector(".game");const afterTribute=await roomState(tributeSetup.session);if(afterTribute.room.status!=="playing"||afterTribute.room.players.some(player=>player.cardCount!==27)||afterTribute.room.players.find(player=>player.seat===afterTribute.game.currentSeat).id!==tributeSetup.tribute.leaderId)throw new Error("tribute did not restore hands or opening lead");await tributePage.close();
  await browser.close();console.log(JSON.stringify({ok:true,checks:{initialCards,...checks,seatActions,playedFaces,audioAssets,audioDurations,tributeChecks},output},null,2));
}finally{server?.kill()}
